/**
 * lib/project-generator/services/export.service.ts
 *
 * Assembles the final `ExportBundle`: a rendered README, optional GitHub
 * templates, and a ZIP archive containing every generated artifact
 * (spec, database migrations, API docs, diagrams, roadmap, deployment
 * guides, testing plan, security plan) as real files with a manifest of
 * SHA-256 checksums.
 *
 * Requires the `archiver` package (`npm install archiver` and, for
 * TypeScript projects, `npm install -D @types/archiver`).
 */

import { createHash } from "node:crypto";
import { PassThrough } from "node:stream";
import { ZipArchive } from "archiver";

import {
  ApiDesign,
  DatabaseSchema,
  DeploymentPlan,
  DiagramSet,
  ExportBundle,
  ExportFormat,
  ExportManifestEntry,
  GithubTemplateSet,
  LicenseType,
  ProjectEstimation,
  ProjectSpec,
  ReadmeDocument,
  Result,
  Roadmap,
  SecurityPlan,
  TestingPlan,
  GenerationError,
  ok,
  err,
  renderReadmeToMarkdown,
  validateExportBundle,
} from "../models";
import { toGenerationError, validationFailedError } from "./errors";
import type { ServiceContext } from "./types";

/** Uploads the finished ZIP bytes somewhere durable and returns its storage path/URL. */
export interface BundleUploader {
  upload(input: { readonly relativePath: string; readonly data: Buffer; readonly contentType: string }): Promise<
    Result<string, GenerationError>
  >;
}

export interface ExportInput {
  readonly spec: ProjectSpec;
  readonly schema: DatabaseSchema;
  readonly apiDesign: ApiDesign;
  readonly roadmap: Roadmap;
  readonly diagrams: DiagramSet;
  readonly deploymentPlan: DeploymentPlan;
  readonly testingPlan: TestingPlan;
  readonly securityPlan: SecurityPlan;
  readonly estimation: ProjectEstimation;
}

function buildReadmeDocument(input: ExportInput): ReadmeDocument {
  const { spec, roadmap, estimation, deploymentPlan } = input;

  return {
    title: spec.title,
    badges: [
      `![License](https://img.shields.io/badge/license-${encodeURIComponent(spec.license)}-blue.svg)`,
      `![Difficulty](https://img.shields.io/badge/difficulty-${encodeURIComponent(spec.difficulty.label)}-orange.svg)`,
    ],
    license: spec.license,
    sections: [
      { heading: "Overview", level: 2, content: `${spec.tagline}\n\n${spec.description}` },
      {
        heading: "Objectives",
        level: 2,
        content: spec.objectives.map((o) => `- ${o.statement}`).join("\n") || "_No objectives specified._",
      },
      {
        heading: "Modules",
        level: 2,
        content: spec.modules
          .map((m) => {
            const features = spec.features.filter((f) => f.moduleId === m.id);
            return `### ${m.name}\n\n${m.description}\n\n${features.map((f) => `- **${f.name}** — ${f.description}`).join("\n")}`;
          })
          .join("\n\n"),
      },
      {
        heading: "Tech Stack",
        level: 2,
        content: spec.techStack.map((t) => `- **${t.name}** (${t.category}, v${t.version}) — ${t.rationale}`).join("\n"),
      },
      {
        heading: "Getting Started",
        level: 2,
        content: [
          "```bash",
          "npm install",
          "cp .env.example .env.local   # fill in the required environment variables",
          "npm run dev",
          "```",
          "",
          `See \`docs/deployment/${deploymentPlan.recommendedTarget}.md\` for production deployment.`,
        ].join("\n"),
      },
      {
        heading: "Roadmap",
        level: 2,
        content: [...roadmap.phases]
          .sort((a, b) => a.order - b.order)
          .map((p) => `- **${p.title}** — ${p.goal}`)
          .join("\n"),
      },
      {
        heading: "Estimation",
        level: 2,
        content:
          `- **Estimated effort:** ${estimation.totalEstimatedHours.min}-${estimation.totalEstimatedHours.max} hours\n` +
          `- **Estimated cost:** $${estimation.estimatedCostUsd.min.toLocaleString()}-$${estimation.estimatedCostUsd.max.toLocaleString()}\n` +
          `- **Estimated timeline:** ${estimation.estimatedTimelineWeeks.min}-${estimation.estimatedTimelineWeeks.max} weeks\n` +
          `- **Recommended team size:** ${estimation.recommendedTeamSize.min}-${estimation.recommendedTeamSize.max} people`,
      },
      {
        heading: "Project Structure",
        level: 2,
        content: ["```", renderFolderTreeText(spec.folderStructure), "```"].join("\n"),
      },
      {
        heading: "Generated by",
        level: 2,
        content: "This project was scaffolded by Prophezy's Project Generator.",
      },
    ],
  };
}

function renderFolderTreeText(node: ProjectSpec["folderStructure"], prefix = ""): string {
  const line = `${prefix}${node.name}${node.type === "directory" ? "/" : ""}`;
  const childLines = node.children.map((child) => renderFolderTreeText(child, `${prefix}  `));
  return [line, ...childLines].join("\n");
}

function buildGithubTemplateSet(spec: ProjectSpec): GithubTemplateSet {
  return {
    contributingMd: [
      `# Contributing to ${spec.title}`,
      "",
      "1. Fork the repository and create a feature branch off `main`.",
      "2. Follow the existing code style and add tests for any new behavior.",
      "3. Run the full test suite before opening a pull request.",
      "4. Open a PR using the provided template and link any related issues.",
    ].join("\n"),
    pullRequestTemplateMd: [
      "## Summary",
      "",
      "## Related issue(s)",
      "",
      "## Checklist",
      "- [ ] Tests added/updated",
      "- [ ] Documentation updated",
      "- [ ] No breaking changes (or called out below)",
    ].join("\n"),
    bugReportIssueTemplateMd: [
      "---",
      "name: Bug report",
      "about: Report a reproducible problem",
      "---",
      "",
      "**Describe the bug**",
      "",
      "**Steps to reproduce**",
      "",
      "**Expected behavior**",
      "",
      "**Environment**",
    ].join("\n"),
    featureRequestIssueTemplateMd: [
      "---",
      "name: Feature request",
      "about: Suggest an idea",
      "---",
      "",
      "**Problem this solves**",
      "",
      "**Proposed solution**",
      "",
      "**Alternatives considered**",
    ].join("\n"),
    codeOwners: "* @maintainers",
  };
}

/** Builds every text file that goes into the export bundle as an in-memory `path -> content` map. */
function buildFileMap(input: ExportInput, readme: ReadmeDocument, github: GithubTemplateSet): Map<string, string> {
  const { spec, schema, apiDesign, roadmap, diagrams, deploymentPlan, testingPlan, securityPlan, estimation } = input;
  const files = new Map<string, string>();

  files.set("README.md", renderReadmeToMarkdown(readme));
  files.set("LICENSE", renderLicenseText(spec.license, spec.title));
  files.set(".github/CONTRIBUTING.md", github.contributingMd);
  files.set(".github/PULL_REQUEST_TEMPLATE.md", github.pullRequestTemplateMd);
  files.set(".github/ISSUE_TEMPLATE/bug_report.md", github.bugReportIssueTemplateMd);
  files.set(".github/ISSUE_TEMPLATE/feature_request.md", github.featureRequestIssueTemplateMd);
  files.set(".github/CODEOWNERS", github.codeOwners);
  files.set(".github/workflows/" + deploymentPlan.pipeline.workflowFileName.split("/").pop(), renderWorkflowYaml(deploymentPlan));

  files.set("docs/project-spec.json", JSON.stringify(spec, null, 2));
  files.set("docs/database-schema.json", JSON.stringify(schema, null, 2));
  files.set("docs/api-design.json", JSON.stringify(apiDesign, null, 2));
  files.set("docs/roadmap.json", JSON.stringify(roadmap, null, 2));
  files.set("docs/estimation.json", JSON.stringify(estimation, null, 2));
  files.set("docs/security-plan.json", JSON.stringify(securityPlan, null, 2));
  files.set("docs/testing-plan.json", JSON.stringify(testingPlan, null, 2));

  for (const diagram of diagrams.diagrams) {
    files.set(`docs/diagrams/${slugify(diagram.title)}.mmd`, diagram.mermaidSource);
  }

  for (const guide of deploymentPlan.guides) {
    files.set(`docs/deployment/${guide.target}.md`, renderDeploymentGuideMarkdown(guide));
  }

  files.set(".env.example", renderEnvExample(deploymentPlan));

  return files;
}

function renderLicenseText(license: LicenseType, projectTitle: string): string {
  const year = new Date().getFullYear();
  if (license === "UNLICENSED" || license === "Proprietary") {
    return `Copyright (c) ${year} ${projectTitle}\n\nAll rights reserved. This software is proprietary and confidential.`;
  }
  return `${license} License\n\nCopyright (c) ${year} ${projectTitle}\n\nSee https://opensource.org/licenses/${license} for the full license text.`;
}

function renderWorkflowYaml(plan: DeploymentPlan): string {
  const jobsYaml = plan.pipeline.jobs
    .map((job) => {
      const stepsYaml = job.steps.map((s) => `      - name: ${s.name}\n        run: ${s.run}`).join("\n");
      return [
        `  ${slugify(job.name)}:`,
        `    runs-on: ${job.runsOn}`,
        "    steps:",
        "      - uses: actions/checkout@v4",
        stepsYaml,
      ].join("\n");
    })
    .join("\n");

  const branches = Array.from(new Set(plan.pipeline.jobs.flatMap((j) => j.triggerBranches))).join(", ");

  return ["name: CI", "", "on:", "  push:", `    branches: [${branches}]`, "  pull_request:", "", "jobs:", jobsYaml].join("\n");
}

function renderDeploymentGuideMarkdown(guide: DeploymentPlan["guides"][number]): string {
  const stepsMd = guide.steps
    .map((s) => `### ${s.order}. ${s.title}\n\n${s.instructions}${s.command ? `\n\n\`\`\`bash\n${s.command}\n\`\`\`` : ""}`)
    .join("\n\n");
  const envMd = guide.environmentVariables
    .map((v) => `| \`${v.key}\` | ${v.required ? "Yes" : "No"} | ${v.secret ? "Yes" : "No"} | ${v.description} |`)
    .join("\n");

  return [
    `# ${guide.title}`,
    "",
    "## Prerequisites",
    guide.prerequisites.map((p) => `- ${p}`).join("\n"),
    "",
    "## Steps",
    stepsMd,
    "",
    "## Environment Variables",
    "| Key | Required | Secret | Description |",
    "|---|---|---|---|",
    envMd,
    "",
    "## Post-Deploy Checklist",
    guide.postDeployChecklist.map((c) => `- [ ] ${c}`).join("\n"),
  ].join("\n");
}

function renderEnvExample(plan: DeploymentPlan): string {
  const seen = new Set<string>();
  const lines: string[] = [];
  for (const guide of plan.guides) {
    for (const envVar of guide.environmentVariables) {
      if (seen.has(envVar.key)) continue;
      seen.add(envVar.key);
      lines.push(`# ${envVar.description}`);
      lines.push(`${envVar.key}=${envVar.secret ? "" : envVar.exampleValue}`);
      lines.push("");
    }
  }
  return lines.join("\n");
}

function slugify(text: string): string {
  return text
    .toLowerCase()
    .trim()
    .replace(/[^a-z0-9]+/g, "-")
    .replace(/(^-|-$)/g, "");
}

/** Streams every file in `fileMap` into a ZIP archive and resolves with the complete buffer. */
async function buildZipBuffer(fileMap: ReadonlyMap<string, string>): Promise<Buffer> {
  return new Promise((resolve, reject) => {
    const archive = new ZipArchive({ zlib: { level: 9 } });
    const passthrough = new PassThrough();
    const chunks: Buffer[] = [];

    passthrough.on("data", (chunk: Buffer) => chunks.push(chunk));
    passthrough.on("end", () => resolve(Buffer.concat(chunks)));
    passthrough.on("error", reject);
    archive.on("error", reject);
    archive.pipe(passthrough);

    for (const [relativePath, content] of fileMap.entries()) {
      archive.append(content, { name: relativePath });
    }

    void archive.finalize();
  });
}

function contentTypeFor(relativePath: string): string {
  if (relativePath.endsWith(".json")) return "application/json";
  if (relativePath.endsWith(".md")) return "text/markdown";
  if (relativePath.endsWith(".yml") || relativePath.endsWith(".yaml")) return "text/yaml";
  if (relativePath.endsWith(".mmd")) return "text/plain";
  return "text/plain";
}

/**
 * Assembles and packages the complete `ExportBundle` for a finished
 * generation: renders README + GitHub templates, writes every artifact
 * as a real file, builds a checksummed manifest, zips everything, and
 * uploads the ZIP via the injected `BundleUploader`.
 */
export async function generateExportBundle(
  input: ExportInput,
  context: ServiceContext,
  uploader: BundleUploader,
  options: { readonly formats?: readonly ExportFormat[]; readonly expiresAt?: string | null } = {}
): Promise<Result<ExportBundle, GenerationError>> {
  const step = "generateExportBundle";
  try {
    const readme = buildReadmeDocument(input);
    const github = buildGithubTemplateSet(input.spec);
    const fileMap = buildFileMap(input, readme, github);

    const manifest: ExportManifestEntry[] = Array.from(fileMap.entries()).map(([relativePath, content]) => {
      const buffer = Buffer.from(content, "utf-8");
      return {
        relativePath,
        sizeBytes: buffer.byteLength,
        checksumSha256: createHash("sha256").update(buffer).digest("hex"),
        mimeType: contentTypeFor(relativePath),
      };
    });

    const zipBuffer = await buildZipBuffer(fileMap);
    const zipRelativePath = `exports/${input.spec.id}.zip`;

    const uploadResult = await uploader.upload({
      relativePath: zipRelativePath,
      data: zipBuffer,
      contentType: "application/zip",
    });
    if (!uploadResult.ok) return uploadResult;

    const totalSizeBytes = manifest.reduce((sum, entry) => sum + entry.sizeBytes, 0);

    const bundle: ExportBundle = {
      id: context.ids.newId(),
      projectSpecId: input.spec.id,
      formats: options.formats ?? [ExportFormat.ZIP, ExportFormat.MARKDOWN, ExportFormat.JSON],
      readme,
      githubTemplates: github,
      manifest,
      storagePath: uploadResult.value,
      totalSizeBytes,
      createdAt: context.clock.nowISO(),
      expiresAt: options.expiresAt ?? null,
    };

    const problems = validateExportBundle(bundle);
    if (problems.length > 0) {
      context.logger.error(`${step}: validation failed`, { problems });
      return err(validationFailedError(step, problems));
    }

    context.logger.info(`${step}: succeeded`, {
      projectSpecId: input.spec.id,
      fileCount: manifest.length,
      totalSizeBytes,
      storagePath: bundle.storagePath,
    });
    return ok(bundle);
  } catch (error) {
    context.logger.error(`${step}: failed`, { error: error instanceof Error ? error.message : String(error) });
    return err(toGenerationError(error, { step }));
  }
}
